services:
  - type: web
    name: deploy-test
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: frankfurt
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    disk:
      name: deploy-test-uploads
      mountPath: /opt/render/project/src/public/uploads
      sizeGB: 1
    envVars:
      - key: NODE_VERSION
        value: 14.21
      - key: NODE_ENV
        value: development
      - key: DATABASE_URL
        fromDatabase:
          name: deploy-test
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true

databases:
  - name: deploy-test
    plan: starter
